import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);
const SUPPORTED_LANGS = ['en', 'vi', 'zh', 'ko'];
const TV_TRANSLATIONS = {
  zh: {
    'Việt Nam': '越南',
    'Xem vị trí': '查看地图',
    'Sắp xếp': '排序',
    'Được ưa chuộng': '推荐',
    'Giá thấp nhất trước': '价格从低到高',
    'Xếp hạng cao nhất trước': '价格从高到低',
    Giá: '价格',
    'Tối thiểu': '最低',
    'Tối đa': '最高',
    'Đánh giá sao': '星级评分',
    'Không có đánh giá': '不按评分筛选',
    'Đặc điểm của đơn đặt chỗ': '预订特色',
    'Chính sách hủy miễn phí / linh hoạt': '免费/灵活取消政策',
    'Xác nhận ngay lập tức': '即时确认',
    'Thời gian': '时间',
    'Dùng ngày nhận / trả phòng ở thanh tìm kiếm phía trên.': '请在顶部搜索栏选择入住/退房日期。',
    'Áp dụng bộ lọc': '应用筛选',
    'Xóa bộ lọc': '清除筛选',
    'Xóa lọc': '清除筛选',
    'Hồ sơ chủ nhà': '房东主页',
    'Không thể tải hồ sơ chủ nhà.': '无法加载房东主页。',
    'Chủ nhà': '房东',
    'chỗ ở của chủ nhà này': '该房东的房源',
    'Xem theo tỉnh/thành': '按省/城市查看',
    'Tất cả': '全部',
    'Chủ nhà này chưa có chỗ ở công khai.': '该房东暂无公开房源。',
    'Quay lại tìm kiếm': '返回搜索',
    'Vị trí đẹp': '位置优越',
    'Hủy miễn phí': '免费取消',
    'Chủ nhà được đánh giá cao': '高评分房东',
    'đánh giá xác thực': '条真实评价',
    đêm: '晚',
    'đánh giá': '条评价',
    Xem: '查看',
    'Xuất sắc': '超棒',
    'Rất tốt': '非常好',
    Tốt: '好',
    'Ổn': '尚可',
    'Điểm đánh giá': '评分',
    'Giá từ': '起价',
    'Đề xuất': '推荐',
    'Giá thấp': '低价',
    'Giá cao': '高价',
    'Điểm 4+': '评分4+',
    'Nguyên căn': '整套',
    'Phòng riêng': '独立房间',
    'Điều hòa': '空调',
    'Kết quả tìm kiếm': '搜索结果',
    'chỗ ở được tìm thấy': '个房源',
    'Không có chỗ ở phù hợp với bộ lọc hiện tại.': '当前筛选条件下没有匹配房源。',
    'Chỗ ở trên bản đồ': '地图房源',
    'nơi ở trong 10 km': '10公里内房源',
    'từ vị trí của bạn': '距你的位置',
    'từ tâm khu vực': '距搜索中心',
    'Không bật vị trí — khoảng cách theo khu vực tìm kiếm.': '未开启定位——距离按搜索区域计算。',
    'Đang hiển thị vị trí thực của bạn trên bản đồ': '正在地图上显示你的位置',
    Đóng: '关闭',
    'Sắp xếp theo': '排序方式',
    'Khoảng cách': '距离',
    'Giá: thấp → cao': '价格：低到高',
    'Giá: cao → thấp': '价格：高到低',
    'Không có chỗ ở phù hợp.': '没有匹配房源。',
    'từ bạn': '距你',
    'từ khu vực': '距区域中心',
    'Tìm trên bản đồ': '在地图上搜索',
    'Tóm tắt chỗ ở': '房源摘要',
    khách: '位客人',
    'phòng ngủ': '间卧室',
    'Xem chi tiết': '查看详情',
    'Không tải được dữ liệu chủ nhà': '无法加载房东数据',
    'Bạn có thông báo mới.': '你有新通知。',
    Khác: '其他',
    'Đã duyệt check-in.': '已确认入住。',
    'Không thể check-in đơn.': '无法办理入住。',
    'Đã check-out xong.': '已完成退房。',
    'Không thể check-out đơn.': '无法办理退房。',
    'Vui lòng nhập tên khách và giờ check-out.': '请输入客人姓名和退房时间。',
    'Đã tạo check-in trực tiếp thành công.': '已成功创建现场入住。',
    'Không thể tạo check-in trực tiếp.': '无法创建现场入住。',
    'Đang xử lý...': '处理中...',
    'Mã CK': '转账码',
    'Phí lưu trú thêm (tích lũy)': '延住累计费用',
    'Danh sách đặt phòng hiện tại và sắp tới': '当前和即将到来的预订',
    'Phòng này chưa có đặt chỗ nào.': '该房间暂无预订。',
    'Trạng thái': '状态',
    'Thanh toán': '支付',
    'Duyệt check-in': '确认入住',
    'Check-out khách': '客人退房',
    'Check-in khách': '客人入住',
    'Khách vãng lai? Mở form để nhập thông tin và thanh toán.': '散客？打开表单填写信息并支付。',
    'Check-in trực tiếp': '现场入住',
    'Tên khách': '客人姓名',
    'Số điện thoại (tuỳ chọn)': '电话（可选）',
    'Tiền mặt': '现金',
    Thẻ: '银行卡',
    'Chuyển khoản': '银行转账',
    'Đã thanh toán': '已支付',
    'Chờ thanh toán': '待支付',
    'Tạo check-in trực tiếp': '创建现场入住',
  },
  ko: {
    'Việt Nam': '베트남',
    'Xem vị trí': '지도 보기',
    'Sắp xếp': '정렬',
    'Được ưa chuộng': '추천순',
    'Giá thấp nhất trước': '낮은 가격순',
    'Xếp hạng cao nhất trước': '높은 가격순',
    Giá: '가격',
    'Tối thiểu': '최소',
    'Tối đa': '최대',
    'Đánh giá sao': '별점',
    'Không có đánh giá': '평점 필터 없음',
    'Đặc điểm của đơn đặt chỗ': '예약 특징',
    'Chính sách hủy miễn phí / linh hoạt': '무료/유연 취소 정책',
    'Xác nhận ngay lập tức': '즉시 확정',
    'Thời gian': '시간',
    'Dùng ngày nhận / trả phòng ở thanh tìm kiếm phía trên.': '상단 검색바에서 체크인/체크아웃 날짜를 선택하세요.',
    'Áp dụng bộ lọc': '필터 적용',
    'Xóa bộ lọc': '필터 초기화',
    'Xóa lọc': '필터 초기화',
    'Hồ sơ chủ nhà': '호스트 프로필',
    'Không thể tải hồ sơ chủ nhà.': '호스트 프로필을 불러올 수 없습니다.',
    'Chủ nhà': '호스트',
    'chỗ ở của chủ nhà này': '이 호스트의 숙소',
    'Xem theo tỉnh/thành': '지역별 보기',
    'Tất cả': '전체',
    'Chủ nhà này chưa có chỗ ở công khai.': '이 호스트는 공개 숙소가 없습니다.',
    'Quay lại tìm kiếm': '검색으로 돌아가기',
    'Vị trí đẹp': '좋은 위치',
    'Hủy miễn phí': '무료 취소',
    'Chủ nhà được đánh giá cao': '평점 높은 호스트',
    'đánh giá xác thực': '개의 검증된 후기',
    đêm: '박',
    'đánh giá': '개 후기',
    Xem: '보기',
    'Xuất sắc': '최고',
    'Rất tốt': '매우 좋음',
    Tốt: '좋음',
    'Ổn': '무난함',
    'Điểm đánh giá': '평점',
    'Giá từ': '최저가',
    'Đề xuất': '추천',
    'Giá thấp': '저가',
    'Giá cao': '고가',
    'Điểm 4+': '평점 4+',
    'Nguyên căn': '집 전체',
    'Phòng riêng': '개인실',
    'Điều hòa': '에어컨',
    'Kết quả tìm kiếm': '검색 결과',
    'chỗ ở được tìm thấy': '개의 숙소',
    'Không có chỗ ở phù hợp với bộ lọc hiện tại.': '현재 필터에 맞는 숙소가 없습니다.',
    'Chỗ ở trên bản đồ': '지도 숙소',
    'nơi ở trong 10 km': '10km 이내 숙소',
    'từ vị trí của bạn': '현재 위치 기준',
    'từ tâm khu vực': '검색 중심 기준',
    'Không bật vị trí — khoảng cách theo khu vực tìm kiếm.': '위치 권한 없음 - 거리 계산은 검색 지역 기준입니다.',
    'Đang hiển thị vị trí thực của bạn trên bản đồ': '지도에 현재 위치를 표시 중입니다',
    Đóng: '닫기',
    'Sắp xếp theo': '정렬 기준',
    'Khoảng cách': '거리',
    'Giá: thấp → cao': '가격: 낮은순',
    'Giá: cao → thấp': '가격: 높은순',
    'Không có chỗ ở phù hợp.': '일치하는 숙소가 없습니다.',
    'từ bạn': '내 위치 기준',
    'từ khu vực': '지역 중심 기준',
    'Tìm trên bản đồ': '지도에서 검색',
    'Tóm tắt chỗ ở': '숙소 요약',
    khách: '명',
    'phòng ngủ': '침실',
    'Xem chi tiết': '상세 보기',
    'Không tải được dữ liệu chủ nhà': '호스트 데이터를 불러올 수 없습니다',
    'Bạn có thông báo mới.': '새 알림이 있습니다.',
    Khác: '기타',
    'Đã duyệt check-in.': '체크인이 승인되었습니다.',
    'Không thể check-in đơn.': '체크인 처리에 실패했습니다.',
    'Đã check-out xong.': '체크아웃이 완료되었습니다.',
    'Không thể check-out đơn.': '체크아웃 처리에 실패했습니다.',
    'Vui lòng nhập tên khách và giờ check-out.': '고객명과 체크아웃 시간을 입력하세요.',
    'Đã tạo check-in trực tiếp thành công.': '현장 체크인이 생성되었습니다.',
    'Không thể tạo check-in trực tiếp.': '현장 체크인 생성에 실패했습니다.',
    'Đang xử lý...': '처리 중...',
    'Mã CK': '이체 코드',
    'Phí lưu trú thêm (tích lũy)': '연장 숙박 누적 요금',
    'Danh sách đặt phòng hiện tại và sắp tới': '현재 및 예정 예약',
    'Phòng này chưa có đặt chỗ nào.': '이 객실에는 예약이 없습니다.',
    'Trạng thái': '상태',
    'Thanh toán': '결제',
    'Duyệt check-in': '체크인 승인',
    'Check-out khách': '체크아웃',
    'Check-in khách': '체크인',
    'Khách vãng lai? Mở form để nhập thông tin và thanh toán.': '워크인 고객인가요? 양식을 열어 정보 입력 및 결제를 진행하세요.',
    'Check-in trực tiếp': '현장 체크인',
    'Tên khách': '고객 이름',
    'Số điện thoại (tuỳ chọn)': '전화번호(선택)',
    'Tiền mặt': '현금',
    Thẻ: '카드',
    'Chuyển khoản': '계좌이체',
    'Đã thanh toán': '결제 완료',
    'Chờ thanh toán': '결제 대기',
    'Tạo check-in trực tiếp': '현장 체크인 생성',
  },
};

const TEXTS = {
  en: {
    headerListProperty: 'List your property',
    headerRegister: 'Register',
    headerSignIn: 'Sign in',
    headerMyBookings: 'My bookings',
    headerSaved: 'Saved',
    headerAccount: 'Account',
    headerLogout: 'Log out',
    navStays: 'Stays',
    navSearch: 'Search',
    navTrips: 'Trips',
    navAdmin: 'Admin',
    navAccount: 'Account',
    homeTitle: 'Find your next stay',
    homeSubtitle1:
      'Search homestays in Vietnam — compare prices and guest reviews, then book with card checkout or bank transfer.',
    homeSubtitle2:
      'Discover beach towns, heritage quarters, and city stays with verified listings, clear policies, and flexible dates.',
    homeSubtitle3:
      'Book with confidence on TRAVEL: secure payments, transparent service fees, and instant confirmation when rooms are free.',
    heroDestination: 'Destination',
    heroWhere: 'Where are you going?',
    heroCheckIn: 'Check-in',
    heroCheckOut: 'Check-out',
    heroGuests: 'Guests',
    heroAdults: 'adults',
    heroSearch: 'Search',
    whyTitle: 'Why book with TRAVEL?',
    aiConfigMissing:
      'AI is off until the server has COHERE_API_KEY, GEMINI_API_KEY (Google), or OPENAI_API_KEY in backend/.env.',
    aiThinking: 'Thinking...',
    aiSend: 'Send',
    aiPlaceholder: 'Describe the stay you want, or ask about payment...',
    aiSorry: 'Sorry, I could not answer.',
    footerPopular: 'Popular with travelers in Vietnam',
    footerShowMore: '+ Show more',
    footerSupport: 'Support',
    footerDiscover: 'Discover',
    footerAccount: 'Account',
    footerHosts: 'Hosts',
    footerAbout: 'About',
    footerHome: 'Home',
    footerSearchStays: 'Search stays',
    footerBestValue: 'Best value',
    footerTopRated: 'Top rated',
    footerSavedHomes: 'Saved homes',
    footerManageListings: 'Manage listings',
    footerHowItWorks: 'How it works',
    footerContact: 'Contact',
    footerInspired: 'UI inspired by leading travel sites.',
    langEnglish: 'English',
    langVietnamese: 'Tiếng Việt',
    langChinese: '中文',
    langKorean: '한국어',
    navHost: 'Host',
    hostHubTitle: 'Host hub',
    hostNavGeneral: 'Overview',
    hostNavBookings: 'Reservations',
    hostNavRoomMap: 'Room map',
    hostNavCreateBooking: 'New stay',
    hostNavFinance: 'Payments',
    hostNavListings: 'Listings',
    hostNavReports: 'Reports & revenue',
    hostNavBankQr: 'Bank / QR',
    hostPillEmpty: 'Vacant',
    hostPillBooked: 'Pre-booked',
    hostPillOccupied: 'In-house',
    hostBadgeVacant: 'Vacant',
    hostBadgeInHouse: 'Guests in house',
    hostBadgeReserved: 'Pre-booked',
    hostCurrentStay: 'Current stay',
    hostUpcomingBooking: 'Upcoming / next booking',
    hostFilterAll: 'All',
    hostSearchPlaceholder: 'Search…',
    hostBookRoom: 'Find stays',
    hostLoading: 'Loading…',
    hostNoRooms: 'No listings match this filter.',
    hostClean: 'Ready',
    hostRoomMenu: 'Room actions',
    hostViewListing: 'View listing',
    hostEditListing: 'Edit in manager',
    hostNoActiveBooking: 'No booking on this row',
    hostBookingsTitle: 'All reservations',
    hostColStay: 'Property',
    hostColGuest: 'Guest',
    hostColDates: 'Stay',
    hostColStatus: 'Booking',
    hostColPayment: 'Payment',
    hostNoBookings: 'No bookings yet.',
    hostListingsTitle: 'Listings',
    hostListingsHint: 'Create and edit homestays, photos, and pricing in the full manager.',
    hostOpenListingsManager: 'Open listing manager',
    hostCreateTitle: 'Guest bookings',
    hostCreateHint: 'Guests book from search and listing pages. You can share a link to your property.',
    hostGoSearch: 'Browse site',
    hostFinanceTitle: 'Income & payouts',
    hostFinanceHint: 'Bank QR and revenue charts live in the manager.',
    hostOpenBank: 'Bank / QR',
    hostOpenRevenue: 'Revenue',
    hostGeneralTitle: 'Host overview',
    hostGeneralBody: 'Use the room map to see occupancy at a glance. Each card is one published homestay.',
    hostGeneralLi1: 'Vacant: no overlapping reservation.',
    hostGeneralLi2: 'Pre-booked: a future stay is scheduled; the unit is empty until check-in.',
    hostGeneralLi3: 'In-house: current stay overlaps today.',
    hostMapHint:
      'Each card is one listing. Colors: in-house (green), pre-booked only (blue), vacant (grey). Manage via the menu (⋮).',
  },
  vi: {
    headerListProperty: 'Đăng chỗ ở',
    headerRegister: 'Đăng ký',
    headerSignIn: 'Đăng nhập',
    headerMyBookings: 'Đặt chỗ của tôi',
    headerSaved: 'Đã lưu',
    headerAccount: 'Tài khoản',
    headerLogout: 'Đăng xuất',
    navStays: 'Chỗ ở',
    navSearch: 'Tìm kiếm',
    navTrips: 'Chuyến đi',
    navAdmin: 'Quản trị',
    navAccount: 'Tài khoản',
    homeTitle: 'Tìm nơi ở tiếp theo của bạn',
    homeSubtitle1:
      'Tìm homestay Việt Nam — so sánh giá và đánh giá khách thật, đặt phòng qua thẻ hoặc chuyển khoản an toàn.',
    homeSubtitle2:
      'Khám phá biển, phố cổ và trung tâm thành phố: tin đăng rõ ràng, chính sách minh bạch, ngày linh hoạt.',
    homeSubtitle3:
      'Đặt chỗ an tâm trên TRAVEL: thanh toán bảo mật, phí dịch vụ rõ ràng, xác nhận ngay khi còn phòng trống.',
    heroDestination: 'Điểm đến',
    heroWhere: 'Bạn muốn đi đâu?',
    heroCheckIn: 'Nhận phòng',
    heroCheckOut: 'Trả phòng',
    heroGuests: 'Khách',
    heroAdults: 'người lớn',
    heroSearch: 'Tìm',
    whyTitle: 'Vì sao nên đặt với TRAVEL?',
    aiConfigMissing:
      'AI đang tắt cho đến khi server có COHERE_API_KEY, GEMINI_API_KEY (Google) hoặc OPENAI_API_KEY trong backend/.env.',
    aiThinking: 'Đang trả lời...',
    aiSend: 'Gửi',
    aiPlaceholder: 'Mô tả nơi ở bạn muốn, hoặc hỏi về thanh toán...',
    aiSorry: 'Xin lỗi, tôi chưa thể trả lời.',
    footerPopular: 'Điểm đến phổ biến tại Việt Nam',
    footerShowMore: '+ Xem thêm',
    footerSupport: 'Hỗ trợ',
    footerDiscover: 'Khám phá',
    footerAccount: 'Tài khoản',
    footerHosts: 'Chủ nhà',
    footerAbout: 'Giới thiệu',
    footerHome: 'Trang chủ',
    footerSearchStays: 'Tìm chỗ ở',
    footerBestValue: 'Giá tốt',
    footerTopRated: 'Đánh giá cao',
    footerSavedHomes: 'Chỗ ở đã lưu',
    footerManageListings: 'Quản lý tin đăng',
    footerHowItWorks: 'Cách hoạt động',
    footerContact: 'Liên hệ',
    footerInspired: 'Giao diện lấy cảm hứng từ các trang du lịch hàng đầu.',
    langEnglish: 'English',
    langVietnamese: 'Tiếng Việt',
    langChinese: '中文',
    langKorean: '한국어',
    navHost: 'Chủ nhà',
    hostHubTitle: 'Bảng chủ nhà',
    hostNavGeneral: 'Thông tin chung',
    hostNavBookings: 'Quản lý đặt phòng',
    hostNavRoomMap: 'Sơ đồ phòng',
    hostNavCreateBooking: 'Tạo đặt phòng',
    hostNavFinance: 'Thu chi',
    hostNavListings: 'Tin đăng',
    hostNavReports: 'Báo cáo & doanh thu',
    hostNavBankQr: 'Ngân hàng / QR',
    hostPillEmpty: 'Trống',
    hostPillBooked: 'Đặt trước',
    hostPillOccupied: 'Có khách',
    hostBadgeVacant: 'Trống',
    hostBadgeInHouse: 'Đang có khách',
    hostBadgeReserved: 'Đặt trước',
    hostCurrentStay: 'Đang lưu trú',
    hostUpcomingBooking: 'Đặt trước / kế tiếp',
    hostFilterAll: 'Tất cả',
    hostSearchPlaceholder: 'Tìm kiếm…',
    hostBookRoom: 'Đặt phòng',
    hostLoading: 'Đang tải…',
    hostNoRooms: 'Không có tin nào khớp bộ lọc.',
    hostClean: 'Sạch',
    hostRoomMenu: 'Thao tác phòng',
    hostViewListing: 'Xem tin',
    hostEditListing: 'Sửa trong quản lý',
    hostNoActiveBooking: 'Chưa có lịch đặt',
    hostBookingsTitle: 'Tất cả đặt phòng',
    hostColStay: 'Chỗ ở',
    hostColGuest: 'Khách',
    hostColDates: 'Thời gian lưu trú',
    hostColStatus: 'Trạng thái',
    hostColPayment: 'Thanh toán',
    hostNoBookings: 'Chưa có đặt phòng.',
    hostListingsTitle: 'Tin đăng',
    hostListingsHint: 'Tạo và chỉnh sửa homestay, ảnh, giá trong trình quản lý đầy đủ.',
    hostOpenListingsManager: 'Mở quản lý tin đăng',
    hostCreateTitle: 'Đặt phòng cho khách',
    hostCreateHint: 'Khách đặt qua trang tìm kiếm và chi tiết tin. Bạn có thể gửi link chỗ ở của mình.',
    hostGoSearch: 'Vào trang tìm kiếm',
    hostFinanceTitle: 'Thu chi',
    hostFinanceHint: 'QR ngân hàng và biểu đồ doanh thu nằm trong trình quản lý.',
    hostOpenBank: 'Ngân hàng / QR',
    hostOpenRevenue: 'Doanh thu',
    hostGeneralTitle: 'Tổng quan chủ nhà',
    hostGeneralBody: 'Dùng sơ đồ phòng để xem tình trạng nhanh. Mỗi thẻ là một homestay đã đăng.',
    hostGeneralLi1: 'Trống: không có đặt chỗ chồng lấn.',
    hostGeneralLi2: 'Đặt trước: đã có lịch sau; chỗ ở đang trống cho đến khi nhận phòng.',
    hostGeneralLi3: 'Có khách: đang trong kỳ lưu trú.',
    hostMapHint:
      'Mỗi thẻ là một tin đăng. Màu: đang có khách (xanh lá), chỉ đặt trước (xanh dương), trống (xám). Thao tác qua menu (⋮).',
  },
};

TEXTS.zh = {
  ...TEXTS.en,
  headerListProperty: '发布房源',
  headerRegister: '注册',
  headerSignIn: '登录',
  headerMyBookings: '我的预订',
  headerSaved: '已收藏',
  headerAccount: '账户',
  headerLogout: '退出登录',
  navStays: '住宿',
  navSearch: '搜索',
  navTrips: '行程',
  navAdmin: '管理',
  navHost: '房东',
  homeTitle: '寻找下一次入住',
  heroDestination: '目的地',
  heroWhere: '你想去哪里？',
  heroCheckIn: '入住',
  heroCheckOut: '退房',
  heroSearch: '搜索',
  langEnglish: 'English',
  langVietnamese: 'Tiếng Việt',
  langChinese: '中文',
  langKorean: '한국어',
  footerHome: '首页',
  footerSearchStays: '搜索住宿',
  footerAccount: '账户',
};

TEXTS.ko = {
  ...TEXTS.en,
  headerListProperty: '숙소 등록',
  headerRegister: '회원가입',
  headerSignIn: '로그인',
  headerMyBookings: '내 예약',
  headerSaved: '저장됨',
  headerAccount: '계정',
  headerLogout: '로그아웃',
  navStays: '숙소',
  navSearch: '검색',
  navTrips: '여행',
  navAdmin: '관리자',
  navHost: '호스트',
  homeTitle: '다음 숙소 찾기',
  heroDestination: '목적지',
  heroWhere: '어디로 가시나요?',
  heroCheckIn: '체크인',
  heroCheckOut: '체크아웃',
  heroSearch: '검색',
  langEnglish: 'English',
  langVietnamese: 'Tiếng Việt',
  langChinese: '中文',
  langKorean: '한국어',
  footerHome: '홈',
  footerSearchStays: '숙소 검색',
  footerAccount: '계정',
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('lang');
    return SUPPORTED_LANGS.includes(saved) ? saved : 'vi';
  });

  const value = useMemo(() => {
    const dictionary = TEXTS[lang] || TEXTS.en;
    const t = (key) => dictionary?.[key] ?? TEXTS.en[key] ?? key;
    const tv = (en, vi) => {
      if (lang === 'vi') return vi;
      if (lang === 'zh') return TV_TRANSLATIONS.zh?.[vi] || TV_TRANSLATIONS.zh?.[en] || en;
      if (lang === 'ko') return TV_TRANSLATIONS.ko?.[vi] || TV_TRANSLATIONS.ko?.[en] || en;
      return en;
    };
    const changeLanguage = (nextLang) => {
      const v = SUPPORTED_LANGS.includes(nextLang) ? nextLang : 'vi';
      setLang(v);
      localStorage.setItem('lang', v);
    };
    return { lang, changeLanguage, t, tv };
  }, [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
