import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const TEXTS = {
  en: {
    headerListProperty: 'List your property',
    headerRegister: 'Register',
    headerSignIn: 'Sign in',
    headerMyBookings: 'My bookings',
    headerSaved: 'Saved',
    headerAccount: 'Account',
    headerLogout: 'Log out',
    navStays: 'Stays',
    navSearch: 'Search',
    navTrips: 'Trips',
    navAdmin: 'Admin',
    navAccount: 'Account',
    homeTitle: 'Find your next stay',
    homeSubtitle1:
      'Search homestays in Vietnam — compare prices and guest reviews, then book with card checkout or bank transfer.',
    homeSubtitle2:
      'Discover beach towns, heritage quarters, and city stays with verified listings, clear policies, and flexible dates.',
    homeSubtitle3:
      'Book with confidence on TRAVEL: secure payments, transparent service fees, and instant confirmation when rooms are free.',
    heroDestination: 'Destination',
    heroWhere: 'Where are you going?',
    heroCheckIn: 'Check-in',
    heroCheckOut: 'Check-out',
    heroGuests: 'Guests',
    heroAdults: 'adults',
    heroSearch: 'Search',
    whyTitle: 'Why book with TRAVEL?',
    aiConfigMissing:
      'AI is off until the server has COHERE_API_KEY, GEMINI_API_KEY (Google), or OPENAI_API_KEY in backend/.env.',
    aiThinking: 'Thinking...',
    aiSend: 'Send',
    aiPlaceholder: 'Describe the stay you want, or ask about payment...',
    aiSorry: 'Sorry, I could not answer.',
    footerPopular: 'Popular with travelers in Vietnam',
    footerShowMore: '+ Show more',
    footerSupport: 'Support',
    footerDiscover: 'Discover',
    footerAccount: 'Account',
    footerHosts: 'Hosts',
    footerAbout: 'About',
    footerHome: 'Home',
    footerSearchStays: 'Search stays',
    footerBestValue: 'Best value',
    footerTopRated: 'Top rated',
    footerSavedHomes: 'Saved homes',
    footerManageListings: 'Manage listings',
    footerHowItWorks: 'How it works',
    footerContact: 'Contact',
    footerInspired: 'UI inspired by leading travel sites.',
    langEnglish: 'English',
    langVietnamese: 'Tiếng Việt',
    navHost: 'Host',
    hostHubTitle: 'Host hub',
    hostNavGeneral: 'Overview',
    hostNavBookings: 'Reservations',
    hostNavRoomMap: 'Room map',
    hostNavCreateBooking: 'New stay',
    hostNavFinance: 'Payments',
    hostNavListings: 'Listings',
    hostNavReports: 'Reports & revenue',
    hostNavBankQr: 'Bank / QR',
    hostPillEmpty: 'Vacant',
    hostPillBooked: 'Pre-booked',
    hostPillOccupied: 'In-house',
    hostBadgeVacant: 'Vacant',
    hostBadgeInHouse: 'Guests in house',
    hostBadgeReserved: 'Pre-booked',
    hostCurrentStay: 'Current stay',
    hostUpcomingBooking: 'Upcoming / next booking',
    hostFilterAll: 'All',
    hostSearchPlaceholder: 'Search…',
    hostBookRoom: 'Find stays',
    hostLoading: 'Loading…',
    hostNoRooms: 'No listings match this filter.',
    hostClean: 'Ready',
    hostRoomMenu: 'Room actions',
    hostViewListing: 'View listing',
    hostEditListing: 'Edit in manager',
    hostNoActiveBooking: 'No booking on this row',
    hostBookingsTitle: 'All reservations',
    hostColStay: 'Property',
    hostColGuest: 'Guest',
    hostColDates: 'Stay',
    hostColStatus: 'Booking',
    hostColPayment: 'Payment',
    hostNoBookings: 'No bookings yet.',
    hostListingsTitle: 'Listings',
    hostListingsHint: 'Create and edit homestays, photos, and pricing in the full manager.',
    hostOpenListingsManager: 'Open listing manager',
    hostCreateTitle: 'Guest bookings',
    hostCreateHint: 'Guests book from search and listing pages. You can share a link to your property.',
    hostGoSearch: 'Browse site',
    hostFinanceTitle: 'Income & payouts',
    hostFinanceHint: 'Bank QR and revenue charts live in the manager.',
    hostOpenBank: 'Bank / QR',
    hostOpenRevenue: 'Revenue',
    hostGeneralTitle: 'Host overview',
    hostGeneralBody: 'Use the room map to see occupancy at a glance. Each card is one published homestay.',
    hostGeneralLi1: 'Vacant: no overlapping reservation.',
    hostGeneralLi2: 'Pre-booked: a future stay is scheduled; the unit is empty until check-in.',
    hostGeneralLi3: 'In-house: current stay overlaps today.',
    hostMapHint:
      'Each card is one listing. Colors: in-house (green), pre-booked only (blue), vacant (grey). Manage via the menu (⋮).',
  },
  vi: {
    headerListProperty: 'Đăng chỗ ở',
    headerRegister: 'Đăng ký',
    headerSignIn: 'Đăng nhập',
    headerMyBookings: 'Đặt chỗ của tôi',
    headerSaved: 'Đã lưu',
    headerAccount: 'Tài khoản',
    headerLogout: 'Đăng xuất',
    navStays: 'Chỗ ở',
    navSearch: 'Tìm kiếm',
    navTrips: 'Chuyến đi',
    navAdmin: 'Quản trị',
    navAccount: 'Tài khoản',
    homeTitle: 'Tìm nơi ở tiếp theo của bạn',
    homeSubtitle1:
      'Tìm homestay Việt Nam — so sánh giá và đánh giá khách thật, đặt phòng qua thẻ hoặc chuyển khoản an toàn.',
    homeSubtitle2:
      'Khám phá biển, phố cổ và trung tâm thành phố: tin đăng rõ ràng, chính sách minh bạch, ngày linh hoạt.',
    homeSubtitle3:
      'Đặt chỗ an tâm trên TRAVEL: thanh toán bảo mật, phí dịch vụ rõ ràng, xác nhận ngay khi còn phòng trống.',
    heroDestination: 'Điểm đến',
    heroWhere: 'Bạn muốn đi đâu?',
    heroCheckIn: 'Nhận phòng',
    heroCheckOut: 'Trả phòng',
    heroGuests: 'Khách',
    heroAdults: 'người lớn',
    heroSearch: 'Tìm',
    whyTitle: 'Vì sao nên đặt với TRAVEL?',
    aiConfigMissing:
      'AI đang tắt cho đến khi server có COHERE_API_KEY, GEMINI_API_KEY (Google) hoặc OPENAI_API_KEY trong backend/.env.',
    aiThinking: 'Đang trả lời...',
    aiSend: 'Gửi',
    aiPlaceholder: 'Mô tả nơi ở bạn muốn, hoặc hỏi về thanh toán...',
    aiSorry: 'Xin lỗi, tôi chưa thể trả lời.',
    footerPopular: 'Điểm đến phổ biến tại Việt Nam',
    footerShowMore: '+ Xem thêm',
    footerSupport: 'Hỗ trợ',
    footerDiscover: 'Khám phá',
    footerAccount: 'Tài khoản',
    footerHosts: 'Chủ nhà',
    footerAbout: 'Giới thiệu',
    footerHome: 'Trang chủ',
    footerSearchStays: 'Tìm chỗ ở',
    footerBestValue: 'Giá tốt',
    footerTopRated: 'Đánh giá cao',
    footerSavedHomes: 'Chỗ ở đã lưu',
    footerManageListings: 'Quản lý tin đăng',
    footerHowItWorks: 'Cách hoạt động',
    footerContact: 'Liên hệ',
    footerInspired: 'Giao diện lấy cảm hứng từ các trang du lịch hàng đầu.',
    langEnglish: 'English',
    langVietnamese: 'Tiếng Việt',
    navHost: 'Chủ nhà',
    hostHubTitle: 'Bảng chủ nhà',
    hostNavGeneral: 'Thông tin chung',
    hostNavBookings: 'Quản lý đặt phòng',
    hostNavRoomMap: 'Sơ đồ phòng',
    hostNavCreateBooking: 'Tạo đặt phòng',
    hostNavFinance: 'Thu chi',
    hostNavListings: 'Tin đăng',
    hostNavReports: 'Báo cáo & doanh thu',
    hostNavBankQr: 'Ngân hàng / QR',
    hostPillEmpty: 'Trống',
    hostPillBooked: 'Đặt trước',
    hostPillOccupied: 'Có khách',
    hostBadgeVacant: 'Trống',
    hostBadgeInHouse: 'Đang có khách',
    hostBadgeReserved: 'Đặt trước',
    hostCurrentStay: 'Đang lưu trú',
    hostUpcomingBooking: 'Đặt trước / kế tiếp',
    hostFilterAll: 'Tất cả',
    hostSearchPlaceholder: 'Tìm kiếm…',
    hostBookRoom: 'Đặt phòng',
    hostLoading: 'Đang tải…',
    hostNoRooms: 'Không có tin nào khớp bộ lọc.',
    hostClean: 'Sạch',
    hostRoomMenu: 'Thao tác phòng',
    hostViewListing: 'Xem tin',
    hostEditListing: 'Sửa trong quản lý',
    hostNoActiveBooking: 'Chưa có lịch đặt',
    hostBookingsTitle: 'Tất cả đặt phòng',
    hostColStay: 'Chỗ ở',
    hostColGuest: 'Khách',
    hostColDates: 'Thời gian lưu trú',
    hostColStatus: 'Trạng thái',
    hostColPayment: 'Thanh toán',
    hostNoBookings: 'Chưa có đặt phòng.',
    hostListingsTitle: 'Tin đăng',
    hostListingsHint: 'Tạo và chỉnh sửa homestay, ảnh, giá trong trình quản lý đầy đủ.',
    hostOpenListingsManager: 'Mở quản lý tin đăng',
    hostCreateTitle: 'Đặt phòng cho khách',
    hostCreateHint: 'Khách đặt qua trang tìm kiếm và chi tiết tin. Bạn có thể gửi link chỗ ở của mình.',
    hostGoSearch: 'Vào trang tìm kiếm',
    hostFinanceTitle: 'Thu chi',
    hostFinanceHint: 'QR ngân hàng và biểu đồ doanh thu nằm trong trình quản lý.',
    hostOpenBank: 'Ngân hàng / QR',
    hostOpenRevenue: 'Doanh thu',
    hostGeneralTitle: 'Tổng quan chủ nhà',
    hostGeneralBody: 'Dùng sơ đồ phòng để xem tình trạng nhanh. Mỗi thẻ là một homestay đã đăng.',
    hostGeneralLi1: 'Trống: không có đặt chỗ chồng lấn.',
    hostGeneralLi2: 'Đặt trước: đã có lịch sau; chỗ ở đang trống cho đến khi nhận phòng.',
    hostGeneralLi3: 'Có khách: đang trong kỳ lưu trú.',
    hostMapHint:
      'Mỗi thẻ là một tin đăng. Màu: đang có khách (xanh lá), chỉ đặt trước (xanh dương), trống (xám). Thao tác qua menu (⋮).',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('lang');
    return saved === 'vi' ? 'vi' : 'en';
  });

  const value = useMemo(() => {
    const t = (key) => TEXTS[lang]?.[key] ?? TEXTS.en[key] ?? key;
    const tv = (en, vi) => (lang === 'vi' ? vi : en);
    const changeLanguage = (nextLang) => {
      const v = nextLang === 'vi' ? 'vi' : 'en';
      setLang(v);
      localStorage.setItem('lang', v);
    };
    return { lang, changeLanguage, t, tv };
  }, [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
